### ISSUE TITLE
auth/internal-error

### ISSUE THREAD

**Issue by manuelwenner** [esausilva/react-firebase-oauth#1]
Hello,

when i try to login with twitter i get the following error 

` {code: "auth/internal-error", message: "Unable to determine the authorization endpoint for…is may be an issue in the provider configuration."}
`

I already created the Firebase App and Authentication. Furthermore i added the domain to the callback url of the twitter app.

Can you please help?

Best Regards
Manuel

**Comment by esausilva** [comment]
Login to Firebase then click Authentication on the left, do you see your account there? Try deleting the account and re-authenticating
